[package]
name = "reflex-format"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "inspect"
path = "src/bin/inspect.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
crc32fast = "1.4"
